[package]
name = "fetcher"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-fetcher = { path = "../" }
async-std = { version = "1", features = ["unstable"] }
atty = "0.2"
better-panic = "0.2"
bytes = "0.5"
enclose = "1"
fomat-macros = "0.3"
futures = "0.3"
futures_codec = "0.4"
http-client =  { version = "1", features = [ "native_client" ]}
pbr = "1"
ron = "0.5"
serde = { version = "1", features = [ "derive" ]}
surf = { version = " = 2.0.0-alpha.0" }
thiserror = "1"
