[package]
name = "fetcher"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-fetcher = { path = "../" }
async-std = { version = "1.9.0", features = ["unstable"] }
atty = "0.2.14"
better-panic = "0.2.0"
fomat-macros = "0.3.1"
futures = "0.3.15"
futures_codec = "0.4.1"
pbr = "1.0.4"
ron = "0.6.4"
serde = { version = "1.0.126", features = [ "derive" ] }
surf = "2.2.0"
thiserror = "1.0.26"
